export const allReviews = [
  {
    id: 1,
    name: "Alice Johnson",
    rating: "5.0 Amazing",
    text: "Best hotel experience ever!",
  },
  {
    id: 2,
    name: "Bob Smith",
    rating: "4.0 Great",
    text: "Loved the service and ambiance.",
  },
  {
    id: 3,
    name: "Cathy Brown",
    rating: "4.5 Excellent",
    text: "Will visit again!",
  },
  {
    id: 4,
    name: "David Lee",
    rating: "3.8 Good",
    text: "Pretty decent overall.",
  },
  { id: 5, name: "Ella Green", rating: "4.9 Superb", text: "Just wow!" },
  {
    id: 6,
    name: "Frank White",
    rating: "4.3 Nice",
    text: "Good value for money.",
  },
  {
    id: 7,
    name: "Grace Kim",
    rating: "4.1 Solid",
    text: "Comfortable and clean.",
  },
  {
    id: 8,
    name: "Henry Miller",
    rating: "5.0 Amazing",
    text: "Perfect vacation!",
  },
  {
    id: 9,
    name: "Isla Turner",
    rating: "3.7 Okay",
    text: "Not bad, not great.",
  },
  {
    id: 10,
    name: "Jack Wilson",
    rating: "4.6 Wonderful",
    text: "Truly relaxing.",
  },
  {
    id: 11,
    name: "Karen Thomas",
    rating: "4.8 Outstanding",
    text: "Can't complain!",
  },
  { id: 12, name: "Leo Adams", rating: "3.5 Average", text: "It was fine." },
  {
    id: 13,
    name: "Mia Scott",
    rating: "4.2 Very good",
    text: "Impressive cleanliness.",
  },
  {
    id: 14,
    name: "Noah Evans",
    rating: "3.9 Decent",
    text: "Good enough for short stay.",
  },
  {
    id: 15,
    name: "Olivia Clark",
    rating: "5.0 Amazing",
    text: "Fabulous rooms and view!",
  },
  {
    id: 16,
    name: "Paul Hall",
    rating: "4.0 Great",
    text: "Everything worked well.",
  },
  {
    id: 17,
    name: "Quinn Lewis",
    rating: "4.4 Very nice",
    text: "Spacious and modern.",
  },
  {
    id: 18,
    name: "Ruby Allen",
    rating: "4.7 Awesome",
    text: "Absolutely lovely staff.",
  },
  { id: 19, name: "Sam Young", rating: "3.6 Fair", text: "Could be better." },
  {
    id: 20,
    name: "Tina King",
    rating: "4.9 Fantastic",
    text: "A luxurious retreat!",
  },
  {
    id: 21,
    name: "Uma Wright",
    rating: "4.2 Very good",
    text: "Well organized.",
  },
  {
    id: 22,
    name: "Victor Hill",
    rating: "3.9 Decent",
    text: "Reasonable stay.",
  },
  {
    id: 23,
    name: "Wendy Moore",
    rating: "5.0 Amazing",
    text: "Excellent hospitality!",
  },
  {
    id: 24,
    name: "Xander Reed",
    rating: "4.1 Solid",
    text: "Nice rooms and breakfast.",
  },
  {
    id: 25,
    name: "Yara Perez",
    rating: "4.6 Wonderful",
    text: "Felt like home!",
  },
  { id: 26, name: "Zack Bell", rating: "4.3 Good", text: "Great location." },
  {
    id: 27,
    name: "Anna Roy",
    rating: "4.8 Excellent",
    text: "Clean and quiet!",
  },
  { id: 28, name: "Brianne Ray", rating: "4.0 Good", text: "Functional stay." },
  {
    id: 29,
    name: "Carlos Fox",
    rating: "3.7 Okay",
    text: "Fine for the price.",
  },
  {
    id: 30,
    name: "Daisy Shaw",
    rating: "4.9 Superb",
    text: "A dream vacation!",
  },
  {
    id: 31,
    name: "Ethan Cruz",
    rating: "4.2 Very good",
    text: "All amenities available.",
  },
  {
    id: 32,
    name: "Fiona West",
    rating: "3.8 Decent",
    text: "Can be improved.",
  },
  {
    id: 33,
    name: "George Stone",
    rating: "4.4 Great",
    text: "Loved the vibes!",
  },
  {
    id: 34,
    name: "Hannah Lowe",
    rating: "5.0 Amazing",
    text: "Would recommend 100%.",
  },
  { id: 35, name: "Ian Black", rating: "3.9 Okay", text: "Just alright." },
  { id: 36, name: "Julia Snow", rating: "4.7 Lovely", text: "Great comfort!" },
  {
    id: 37,
    name: "Kevin Dale",
    rating: "4.5 Awesome",
    text: "Impressive service.",
  },
  {
    id: 38,
    name: "Luna Quinn",
    rating: "4.6 Great",
    text: "Great food and rooms!",
  },
  {
    id: 39,
    name: "Mason Drake",
    rating: "4.3 Good",
    text: "Clean and spacious.",
  },
  {
    id: 40,
    name: "Nina Frost",
    rating: "4.8 Amazing",
    text: "Loved every second!",
  },
];
